// Generated by CoffeeScript 1.7.1
(function() {
  var app, config, db, express, fs, link, mongoose, path, port, redis, ret;

  express = require('express');

  path = require('path');

  redis = require('redis');

  fs = require('fs');

  config = require('./configure/config');

  mongoose = require('mongoose');

  link = require('./models/link').linkModel;

  app = express();

  db = mongoose.connection;

  db.on("error", function(err) {
    return console.log("Mongo Error " + err);
  });

  mongoose.connect('mongodb://localhost/lnkr');

  config.config(app);

  app.get('/api/test', function(req, res) {
    return res.json({
      'test': 'testdata'
    });
  });

  app.post('/api/links', function(req, res) {
    console.log('test');
    return console.log(req.body);
  });

  app.get('/api/links', function(req, res) {
    return link.find(function(err, links) {
      if (err) {
        console.log(err);
        return;
      }
      return console.log(links);
    });
  });


  /*
  app.get '/readitem', (req, res) ->
      console.log('')
  
  app.get '/readitems', (req, res) ->
      console.log('readitems')
       *db.set('key', 'val', redis.print)
      db.hgetall 'test1', (err, obj) ->
          console.log 'getting all'
          console.log(obj)
          res.json(obj)
  
  app.post '/readitem', (req, res) ->
      console.log 'post readitem'
      console.log(req.body)
      console.log db.hmset 'test1', 'name', req.body.name, 'link', req.body.link, (err, obj) ->
          console.log('saved')
          res.json({ status: 'success' })
   */

  port = app.get('port');

  ret = app.listen(port, function() {
    return console.log('api connected on port ' + port);
  });

}).call(this);

//# sourceMappingURL=webAPI.map
